version: "3"

services:
  postgres:
    image: postgres:9.5-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gisting
      POSTGRES_PASSWORD: gisting
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
